### ISSUE TITLE
Compatible with c++11

### ISSUE THREAD

**Issue by neomissing** [fantasy-peak/ypp#1]
Could you consider compatibility with c++11? c++17 has high requirements on the compiler.

**Comment by fantasy-peak** [comment]
> Could you consider compatibility with c++11? c++17 has high requirements on the compiler.

currently supports enum using the magic_enum library,magin_enum only cpp17,i will Consider adding a cpp11 support,std::optional will be replaced with tl::optional

**Comment by fantasy-peak** [comment]
> > Could you consider compatibility with c++11? c++17 has high requirements on the compiler.
> 
> currently supports enum using the magic_enum library,magin_enum only cpp17,i will Consider adding a cpp11 support,std::optional will be replaced with tl::optional

Add a cpp11 branch now @neomissing
